name: Tour of Heroes CI

env:
  node-version: 16.x

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

  # ESLint and Angular-ESLint are not added yet
  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ env.node-version }}
  #         cache: yarn
  #     - name: Install dependencies
  #       run: yarn install

  #     - name: Lint
  #       run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test --max-parallel=2
